In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
v1 = [2,5,4,7]
v2 = np.array([2,5,4,7])
v3 = np.array([[2], [5], [4], [7]])
v4 = v2.T
print(v1, v2, v3, v4)

[2, 5, 4, 7] [2 5 4 7] [[2]
 [5]
 [4]
 [7]] [2 5 4 7]


In [5]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])

v3 = 4*v1 - 2*v2
print(v3)

[ 0 18 16 24]


In [6]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])

v3 = v1 - v2
print(v3)

[-2  4  4  5]


In [7]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
dp = np.dot(v1,v2)
print(dp)

27


In [8]:
v1 = np.array([2,5,4])
v2 = np.array([4,1,0,2])
dp = np.dot(v1,v2)
print(dp)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [9]:
l1 = 1
l2 = 2
l3 = -3

v1 = np.array([4,5,1])
v2 = np.array([-4,0,-4])
v3 = np.array([1,3,2])

l1*v1 + l2*v2 + l3*v3

array([ -7,  -4, -13])

In [11]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
op = np.outer(v1,v2)
ip = np.dot(v1,v2)
print(op)
print(ip)

[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]
27


In [12]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
v1*v2

array([ 8,  5,  0, 14])

In [14]:
v = np.array([2,5,4,7])

vMag = np.linalg.norm(v)

v_unit = v/vMag
print(vMag)
print(v_unit)

9.695359714832659
[0.20628425 0.51571062 0.4125685  0.72199487]
